---
abstract: 'Create Abstract Syntax Tree for Perl5'
author:
  - 'Masaaki Goshima (goccy) <goccy54@gmail.com>'
build_requires:
  Compiler::Lexer: 0.13
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 2.21
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
  Module::Build::XSUtil: 0.02
dynamic_config: 0
generated_by: 'Minilla/v0.6.5, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Compiler-Parser
no_index:
  directory:
    - t
    - examples
    - builder
provides:
  Compiler::Parser:
    file: lib/Compiler/Parser.pm
    version: 0.02
  Compiler::Parser::AST:
    file: lib/Compiler/Parser/AST.pm
  Compiler::Parser::AST::Renderer:
    file: lib/Compiler/Parser/AST/Renderer.pm
  Compiler::Parser::AST::Renderer::Engine:
    file: lib/Compiler/Parser/AST/Renderer/Engine.pm
  Compiler::Parser::AST::Renderer::Engine::Graphviz:
    file: lib/Compiler/Parser/AST/Renderer/Engine/Graphviz.pm
  Compiler::Parser::AST::Renderer::Engine::Text:
    file: lib/Compiler/Parser/AST/Renderer/Engine/Text.pm
  Compiler::Parser::Node:
    file: lib/Compiler/Parser/Node.pm
  Compiler::Parser::Node::Array:
    file: lib/Compiler/Parser/Node/Array.pm
  Compiler::Parser::Node::ArrayRef:
    file: lib/Compiler/Parser/Node/ArrayRef.pm
  Compiler::Parser::Node::Block:
    file: lib/Compiler/Parser/Node/Block.pm
  Compiler::Parser::Node::Branch:
    file: lib/Compiler/Parser/Node/Branch.pm
  Compiler::Parser::Node::Dereference:
    file: lib/Compiler/Parser/Node/Dereference.pm
  Compiler::Parser::Node::ElseStmt:
    file: lib/Compiler/Parser/Node/ElseStmt.pm
  Compiler::Parser::Node::ForStmt:
    file: lib/Compiler/Parser/Node/ForStmt.pm
  Compiler::Parser::Node::ForeachStmt:
    file: lib/Compiler/Parser/Node/ForeachStmt.pm
  Compiler::Parser::Node::Function:
    file: lib/Compiler/Parser/Node/Function.pm
  Compiler::Parser::Node::FunctionCall:
    file: lib/Compiler/Parser/Node/FunctionCall.pm
  Compiler::Parser::Node::Hash:
    file: lib/Compiler/Parser/Node/Hash.pm
  Compiler::Parser::Node::HashRef:
    file: lib/Compiler/Parser/Node/HashRef.pm
  Compiler::Parser::Node::IfStmt:
    file: lib/Compiler/Parser/Node/IfStmt.pm
  Compiler::Parser::Node::Leaf:
    file: lib/Compiler/Parser/Node/Leaf.pm
  Compiler::Parser::Node::List:
    file: lib/Compiler/Parser/Node/List.pm
  Compiler::Parser::Node::Module:
    file: lib/Compiler/Parser/Node/Module.pm
  Compiler::Parser::Node::Package:
    file: lib/Compiler/Parser/Node/Package.pm
  Compiler::Parser::Node::RegPrefix:
    file: lib/Compiler/Parser/Node/RegPrefix.pm
  Compiler::Parser::Node::Return:
    file: lib/Compiler/Parser/Node/Return.pm
  Compiler::Parser::Node::SingleTermOperator:
    file: lib/Compiler/Parser/Node/SingleTermOperator.pm
  Compiler::Parser::Node::WhileStmt:
    file: lib/Compiler/Parser/Node/WhileStmt.pm
requires:
  XSLoader: 0.02
  perl: 5.008001
resources:
  bugtracker: https://github.com/goccy/p5-Compiler-Parser/issues
  homepage: https://github.com/goccy/p5-Compiler-Parser
  repository: git://github.com/goccy/p5-Compiler-Parser.git
version: 0.02
x_contributors:
  - 'masaaki.goshima <masaaki.goshima@mixi.co.jp>'
